delete from SuperPower;
delete from SuperHero;
delete from SuperHeroPowers;
delete from Address;
delete from Organization;
delete from SuperHeroOrg;
delete from Location;
delete from Sighting;

insert into SuperPower(Power, Description) values ('Teleportation', 'Teleportation or teletransportation is the theoretical transfer of matter or energy from one point to another without traversing the physical space between them.');
insert into SuperPower(Power, Description) values ('Magic', 'Magic or sorcery is the use of rituals, symbols, actions, gestures, and language with the aim of utilizing supernatural forces');
insert into SuperPower(Power, Description) values ('Invisibility', 'Invisibility is the state of an object that cannot be seen.');
insert into SuperPower(Power, Description) values ('Immortality','Immortality is eternal life, the ability to live forever');
insert into SuperPower(Power, Description) values ('Telepathy','Telepathy is the purported transmission of information from one person to another without using any of our known sensory channels or physical interaction.');
insert into SuperPower(Power, Description) values ('Time travel','Time travel is the concept of movement between certain points in time, analogous to movement between different points in space by an object or a person');
insert into SuperPower(Power, Description) values ('Flight','Flight is the process by which an object moves, through an atmosphere or beyond it, as in the case of spaceflight');
insert into SuperPower(Power, Description) values ('X-ray vision','X-ray vision is the ability to see through physical objects at the discretion of the holder of this superpower');
insert into SuperPower(Power, Description) values ('Precognition','Precognition, also called prescience, future vision, future sight is the ability to see events in the future.'); 
insert into SuperPower(Power, Description) values ('Disguise','A disguise can be anything which conceals or changes a persons physical appearance');

insert into SuperHero (SuperName, Description, Gender) values ('Superman', 'Using his immense solar-fueled powers, Superman defends mankind against all manner of threats while championing truth, justice and the American way!', 'Male');
insert into SuperHero (SuperName, Description, Gender) values ('Batman', 'Costumed as a bat to prey on criminals\'s fears, and utilizing a high-tech arsenal, Batman trained extensively to achieve mental and physical perfection, mastering martial arts, detective skills, and criminal psychology', 'Male');
insert into SuperHero (SuperName, Description, Gender) values ('Spider-man', 'Spider-Man has spider-like abilities including superHero strength and the ability to cling to most surfaces. He is also extremely agile and has amazing reflexes. Spider-Man also has a â€œspider sense,â€? that warns him of impending danger.', 'Male');
insert into SuperHero (SuperName, Description, Gender) values ('Iron Man', ' Iron man uses his vast resources and intellect to make the world a better place. His super hero identity led him to become the founding member of the Avengers.', 'Male');
insert into SuperHero (SuperName, Description, Gender) values ('Hulk', 'After being bombarded with a massive dose of gamma radiation while saving a young man\'s life during the testing of an experimental bomb, Dr. Robert Bruce Banner was transformed into the Incredible Hulk', 'Male'); 

insert into SuperHeroPowers(SuperHeroId, SuperPowerId) values(1, 1);
insert into SuperHeroPowers(SuperHeroId, SuperPowerId) values(1, 3);
insert into SuperHeroPowers(SuperHeroId, SuperPowerId) values(1, 7);
insert into SuperHeroPowers(SuperHeroId, SuperPowerId) values(1, 8);
insert into SuperHeroPowers(SuperHeroId, SuperPowerId) values(2, 3);
insert into SuperHeroPowers(SuperHeroId, SuperPowerId) values(2, 4);
insert into SuperHeroPowers(SuperHeroId, SuperPowerId) values(2, 5);
insert into SuperHeroPowers(SuperHeroId, SuperPowerId) values(2, 7);
insert into SuperHeroPowers(SuperHeroId, SuperPowerId) values(2, 10);

insert into Address (Street, City, State, Country, PostalCode) values ('791 Susan Road', 'Atlanta', 'Georgia', 'United States', '30375');
insert into Address (Street, City, State, Country, PostalCode) values ('5 Darwin Parkway', 'Waltham', 'Massachusetts', 'United States', '02453');
insert into Address (Street, City, State, Country, PostalCode) values ('46 Golden Leaf Point', 'Davenport', 'Iowa', 'United States', '52809');
insert into Address (Street, City, State, Country, PostalCode) values ('23 Mosinee Center', 'Denver', 'Colorado', 'United States', '80228');
insert into Address (Street, City, State, Country, PostalCode) values ('726 Haas Place', 'Long Beach', 'California', 'United States', '90847');
insert into Address (Street, City, State, Country, PostalCode) values ('9682 Summer Ridge Avenue', 'Rochester', 'New York', 'United States', '14614');
insert into Address (Street, City, State, Country, PostalCode) values ('2916 Moulton Circle', 'Salt Lake City', 'Utah', 'United States', '84140');
insert into Address (Street, City, State, Country, PostalCode) values ('431 Becker Point', 'Denver', 'Colorado', 'United States', '80209');
insert into Address (Street, City, State, Country, PostalCode) values ('94618 Mendota Lane', 'Evansville', 'Indiana', 'United States', '47712');
insert into Address (Street, City, State, Country, PostalCode) values ('637 Linden Junction', 'Miami', 'Florida', 'United States', '33233');
insert into Address (Street, City, State, Country, PostalCode) values ('2275 Village Green Alley', 'Winston Salem', 'North Carolina', 'United States', '27110');
insert into Address (Street, City, State, Country, PostalCode) values ('724 Morrow Junction', 'Pittsburgh', 'Pennsylvania', 'United States', '15250');
insert into Address (Street, City, State, Country, PostalCode) values ('85 1st Way', 'Grand Forks', 'North Dakota', 'United States', '58207');
insert into Address (Street, City, State, Country, PostalCode) values ('2 Morningstar Junction', 'Minneapolis', 'Minnesota', 'United States', '55412');
insert into Address (Street, City, State, Country, PostalCode) values ('3 West Drive', 'Bismarck', 'North Dakota', 'United States', '58505');
insert into Address (Street, City, State, Country, PostalCode) values ('630 Forster Circle', 'Knoxville', 'Tennessee', 'United States', '37914');
insert into Address (Street, City, State, Country, PostalCode) values ('88 Vidon Plaza', 'El Paso', 'Texas', 'United States', '79940');
insert into Address (Street, City, State, Country, PostalCode) values ('995 Hoard Terrace', 'San Francisco', 'California', 'United States', '94110');
insert into Address (Street, City, State, Country, PostalCode) values ('504 Mesta Trail', 'Greenville', 'South Carolina', 'United States', '29615');
insert into Address (Street, City, State, Country, PostalCode) values ('53 Coleman Lane', 'Washington', 'District of Columbia', 'United States', '20508');
insert into Address (Street, City, State, Country, PostalCode) values ('323 Hoffman Way', 'Phoenix', 'Arizona', 'United States', '85072');
insert into Address (Street, City, State, Country, PostalCode) values ('90509 Maple Wood Lane', 'Houston', 'Texas', 'United States', '77255');
insert into Address (Street, City, State, Country, PostalCode) values ('74607 Westridge Parkway', 'Columbia', 'Missouri', 'United States', '65218');
insert into Address (Street, City, State, Country, PostalCode) values ('6645 Talisman Way', 'San Antonio', 'Texas', 'United States', '78205');
insert into Address (Street, City, State, Country, PostalCode) values ('14225 5th Pass', 'Las Vegas', 'Nevada', 'United States', '89125');
insert into Address (Street, City, State, Country, PostalCode) values ('507 Kensington Lane', 'Brockton', 'Massachusetts', 'United States', '02405');
insert into Address (Street, City, State, Country, PostalCode) values ('220 Fulton Circle', 'Fayetteville', 'North Carolina', 'United States', '28305');
insert into Address (Street, City, State, Country, PostalCode) values ('7898 Forest Trail', 'Louisville', 'Kentucky', 'United States', '40256');
insert into Address (Street, City, State, Country, PostalCode) values ('6 Straubel Pass', 'West Palm Beach', 'Florida', 'United States', '33411');
insert into Address (Street, City, State, Country, PostalCode) values ('01862 Waywood Point', 'Concord', 'California', 'United States', '94522');
insert into Address (Street, City, State, Country, PostalCode) values ('94 Maryland Point', 'Springfield', 'Massachusetts', 'United States', '01105');
insert into Address (Street, City, State, Country, PostalCode) values ('84 Gerald Place', 'Evansville', 'Indiana', 'United States', '47719');
insert into Address (Street, City, State, Country, PostalCode) values ('3592 7th Plaza', 'Chico', 'California', 'United States', '95973');
insert into Address (Street, City, State, Country, PostalCode) values ('4 Marcy Hill', 'Grand Rapids', 'Michigan', 'United States', '49560');
insert into Address (Street, City, State, Country, PostalCode) values ('1 Sage Center', 'Birmingham', 'Alabama', 'United States', '35290');
insert into Address (Street, City, State, Country, PostalCode) values ('862 Moulton Place', 'Detroit', 'Michigan', 'United States', '48217');
insert into Address (Street, City, State, Country, PostalCode) values ('6 Sutherland Street', 'San Antonio', 'Texas', 'United States', '78296');
insert into Address (Street, City, State, Country, PostalCode) values ('98516 Scofield Hill', 'Columbia', 'South Carolina', 'United States', '29220');
insert into Address (Street, City, State, Country, PostalCode) values ('8890 Roxbury Court', 'Lake Charles', 'Louisiana', 'United States', '70607');
insert into Address (Street, City, State, Country, PostalCode) values ('4 Bowman Crossing', 'Macon', 'Georgia', 'United States', '31296');
insert into Address (Street, City, State, Country, PostalCode) values ('2303 David Drive', 'Orlando', 'Florida', 'United States', '32813');
insert into Address (Street, City, State, Country, PostalCode) values ('44 Hovde Court', 'Colorado Springs', 'Colorado', 'United States', '80910');
insert into Address (Street, City, State, Country, PostalCode) values ('3 Novick Pass', 'Inglewood', 'California', 'United States', '90305');
insert into Address (Street, City, State, Country, PostalCode) values ('523 Bay Pass', 'Raleigh', 'North Carolina', 'United States', '27610');
insert into Address (Street, City, State, Country, PostalCode) values ('09127 Surrey Park', 'Saint Louis', 'Missouri', 'United States', '63126');
insert into Address (Street, City, State, Country, PostalCode) values ('955 Pepper Wood Way', 'Monticello', 'Minnesota', 'United States', '55590');
insert into Address (Street, City, State, Country, PostalCode) values ('1476 Red Cloud Road', 'Knoxville', 'Tennessee', 'United States', '37995');
insert into Address (Street, City, State, Country, PostalCode) values ('26 Holmberg Road', 'Birmingham', 'Alabama', 'United States', '35285');
insert into Address (Street, City, State, Country, PostalCode) values ('429 Mitchell Street', 'Honolulu', 'Hawaii', 'United States', '96845');
insert into Address (Street, City, State, Country, PostalCode) values ('40 Bay Junction', 'Springfield', 'Massachusetts', 'United States', '01105');
insert into Address (Street, City, State, Country, PostalCode) values ('643 Everett Pass', 'Athens', 'Georgia', 'United States', '30605');
insert into Address (Street, City, State, Country, PostalCode) values ('80966 Del Mar Street', 'Akron', 'Ohio', 'United States', '44393');
insert into Address (Street, City, State, Country, PostalCode) values ('2 Petterle Street', 'Tuscaloosa', 'Alabama', 'United States', '35487');
insert into Address (Street, City, State, Country, PostalCode) values ('939 Arapahoe Park', 'San Bernardino', 'California', 'United States', '92405');
insert into Address (Street, City, State, Country, PostalCode) values ('536 Debs Way', 'Sacramento', 'California', 'United States', '94297');
insert into Address (Street, City, State, Country, PostalCode) values ('0 Arapahoe Street', 'Atlanta', 'Georgia', 'United States', '31106');
insert into Address (Street, City, State, Country, PostalCode) values ('569 Fairfield Place', 'Fort Worth', 'Texas', 'United States', '76147');
insert into Address (Street, City, State, Country, PostalCode) values ('9 Blue Bill Park Trail', 'Honolulu', 'Hawaii', 'United States', '96825');
insert into Address (Street, City, State, Country, PostalCode) values ('24005 Doe Crossing Point', 'Peoria', 'Illinois', 'United States', '61605');
insert into Address (Street, City, State, Country, PostalCode) values ('35870 Garrison Road', 'Youngstown', 'Ohio', 'United States', '44555');
insert into Address (Street, City, State, Country, PostalCode) values ('47213 Ridgeway Park', 'Los Angeles', 'California', 'United States', '90081');
insert into Address (Street, City, State, Country, PostalCode) values ('4 Fairview Hill', 'Des Moines', 'Iowa', 'United States', '50981');
insert into Address (Street, City, State, Country, PostalCode) values ('44311 Welch Parkway', 'Atlanta', 'Georgia', 'United States', '30380');
insert into Address (Street, City, State, Country, PostalCode) values ('770 Hagan Terrace', 'Harrisburg', 'Pennsylvania', 'United States', '17121');
insert into Address (Street, City, State, Country, PostalCode) values ('4611 Cody Pass', 'Louisville', 'Kentucky', 'United States', '40287');
insert into Address (Street, City, State, Country, PostalCode) values ('98 Debra Lane', 'Monroe', 'Louisiana', 'United States', '71208');
insert into Address (Street, City, State, Country, PostalCode) values ('36 Helena Way', 'Detroit', 'Michigan', 'United States', '48242');
insert into Address (Street, City, State, Country, PostalCode) values ('7240 Sage Crossing', 'Tampa', 'Florida', 'United States', '33673');
insert into Address (Street, City, State, Country, PostalCode) values ('16794 Bunker Hill Court', 'Palm Bay', 'Florida', 'United States', '32909');
insert into Address (Street, City, State, Country, PostalCode) values ('6 Menomonie Plaza', 'Charlottesville', 'Virginia', 'United States', '22903');
insert into Address (Street, City, State, Country, PostalCode) values ('35 Artisan Parkway', 'Washington', 'District of Columbia', 'United States', '20456');
insert into Address (Street, City, State, Country, PostalCode) values ('8363 Pearson Drive', 'Memphis', 'Tennessee', 'United States', '38161');
insert into Address (Street, City, State, Country, PostalCode) values ('6 Corry Way', 'Bakersfield', 'California', 'United States', '93381');
insert into Address (Street, City, State, Country, PostalCode) values ('4 Schiller Way', 'Zephyrhills', 'Florida', 'United States', '33543');
insert into Address (Street, City, State, Country, PostalCode) values ('801 Arrowood Point', 'Los Angeles', 'California', 'United States', '90065');
insert into Address (Street, City, State, Country, PostalCode) values ('93379 Dennis Street', 'Corpus Christi', 'Texas', 'United States', '78415');
insert into Address (Street, City, State, Country, PostalCode) values ('39495 Toban Center', 'Miami', 'Florida', 'United States', '33169');
insert into Address (Street, City, State, Country, PostalCode) values ('5 Declaration Drive', 'San Antonio', 'Texas', 'United States', '78255');
insert into Address (Street, City, State, Country, PostalCode) values ('906 Cottonwood Hill', 'Richmond', 'Virginia', 'United States', '23293');
insert into Address (Street, City, State, Country, PostalCode) values ('774 Prairieview Lane', 'Los Angeles', 'California', 'United States', '90005');
insert into Address (Street, City, State, Country, PostalCode) values ('78 Esker Road', 'Portland', 'Oregon', 'United States', '97221');
insert into Address (Street, City, State, Country, PostalCode) values ('9 Trailsway Junction', 'Arlington', 'Virginia', 'United States', '22225');
insert into Address (Street, City, State, Country, PostalCode) values ('2082 Stephen Court', 'Houston', 'Texas', 'United States', '77075');
insert into Address (Street, City, State, Country, PostalCode) values ('78 Westend Plaza', 'Boston', 'Massachusetts', 'United States', '02298');
insert into Address (Street, City, State, Country, PostalCode) values ('619 Glendale Junction', 'Ventura', 'California', 'United States', '93005');
insert into Address (Street, City, State, Country, PostalCode) values ('0 Havey Crossing', 'Sioux City', 'Iowa', 'United States', '51110');
insert into Address (Street, City, State, Country, PostalCode) values ('445 Old Gate Junction', 'Las Vegas', 'Nevada', 'United States', '89125');
insert into Address (Street, City, State, Country, PostalCode) values ('1845 Spenser Alley', 'Olympia', 'Washington', 'United States', '98506');
insert into Address (Street, City, State, Country, PostalCode) values ('4130 Thompson Place', 'New York City', 'New York', 'United States', '10249');
insert into Address (Street, City, State, Country, PostalCode) values ('37 Ramsey Road', 'Lubbock', 'Texas', 'United States', '79491');
insert into Address (Street, City, State, Country, PostalCode) values ('84183 Northport Hill', 'Garden Grove', 'California', 'United States', '92645');
insert into Address (Street, City, State, Country, PostalCode) values ('6 Sachtjen Drive', 'Santa Monica', 'California', 'United States', '90410');
insert into Address (Street, City, State, Country, PostalCode) values ('6 Buhler Point', 'Washington', 'District of Columbia', 'United States', '20244');
insert into Address (Street, City, State, Country, PostalCode) values ('71 Hallows Park', 'Fort Smith', 'Arkansas', 'United States', '72905');
insert into Address (Street, City, State, Country, PostalCode) values ('17 Kingsford Street', 'Austin', 'Texas', 'United States', '78732');
insert into Address (Street, City, State, Country, PostalCode) values ('41 Dakota Crossing', 'Topeka', 'Kansas', 'United States', '66611');
insert into Address (Street, City, State, Country, PostalCode) values ('2653 Corry Hill', 'Des Moines', 'Iowa', 'United States', '50936');
insert into Address (Street, City, State, Country, PostalCode) values ('2983 Dayton Avenue', 'Wilmington', 'Delaware', 'United States', '19892');
insert into Address (Street, City, State, Country, PostalCode) values ('63 Maple Wood Parkway', 'San Francisco', 'California', 'United States', '94137');
insert into Address (Street, City, State, Country, PostalCode) values ('8553 Nobel Way', 'Philadelphia', 'Pennsylvania', 'United States', '19104');
insert into Address (Street, City, State, Country, PostalCode) values ('55 Glendale Junction', 'Roanoke', 'Virginia', 'United States', '24020');
insert into Address (Street, City, State, Country, PostalCode) values ('8 Hansons Park', 'Chicago', 'Illinois', 'United States', '60604');
insert into Address (Street, City, State, Country, PostalCode) values ('1613 Service Crossing', 'Montpelier', 'Vermont', 'United States', '05609');
insert into Address (Street, City, State, Country, PostalCode) values ('1 Annamark Crossing', 'San Mateo', 'California', 'United States', '94405');
insert into Address (Street, City, State, Country, PostalCode) values ('53048 Forest Run Street', 'Washington', 'District of Columbia', 'United States', '20397');
insert into Address (Street, City, State, Country, PostalCode) values ('199 Heffernan Parkway', 'Houston', 'Texas', 'United States', '77206');
insert into Address (Street, City, State, Country, PostalCode) values ('85 Park Meadow Place', 'Greenville', 'South Carolina', 'United States', '29610');
insert into Address (Street, City, State, Country, PostalCode) values ('152 Kedzie Avenue', 'San Diego', 'California', 'United States', '92196');
insert into Address (Street, City, State, Country, PostalCode) values ('4 Menomonie Court', 'Topeka', 'Kansas', 'United States', '66617');

insert into Organization (`Name`, Description, AddressId) values ('The Fantastic Four', '', 20);
insert into Organization (`Name`, Description, AddressId) values ('Avengers', '',35);
insert into Organization (`Name`, Description, AddressId) values ('Justice League', '',10);
insert into Organization (`Name`, Description, AddressId) values ('X-Force', '' , 11);
insert into Organization (`Name`, Description, AddressId) values ('Squadron Supreme', '' ,15);
insert into Organization (`Name`, Description, AddressId) values ('Defenders', '' ,50);
insert into Organization (`Name`, Description, AddressId) values ('The Watchmen', '' ,75);
insert into Organization (`Name`, Description, AddressId) values ('The X-men', '' ,89);
insert into Organization (`Name`, Description, AddressId) values ('Superman Squad', '' ,67);
insert into Organization (`Name`, Description, AddressId) values ('S.H.I.E.L.D', '' ,102);

insert into SuperHeroOrg(SuperHeroId, OrgId) values(1, 2);
insert into SuperHeroOrg(SuperHeroId, OrgId) values(1, 7);
insert into SuperHeroOrg(SuperHeroId, OrgId) values(1, 9);
insert into SuperHeroOrg(SuperHeroId, OrgId) values(2, 4);
insert into SuperHeroOrg(SuperHeroId, OrgId) values(2, 5);
insert into SuperHeroOrg(SuperHeroId, OrgId) values(3, 6);
insert into SuperHeroOrg(SuperHeroId, OrgId) values(3, 7);
insert into SuperHeroOrg(SuperHeroId, OrgId) values(3, 1);
insert into SuperHeroOrg(SuperHeroId, OrgId) values(4, 3);
insert into SuperHeroOrg(SuperHeroId, OrgId) values(5, 6);
insert into SuperHeroOrg(SuperHeroId, OrgId) values(5, 10);

insert into Location (`Name`,Description, AddressId) values("Mall of America", "Mall located in the Twin Cities", 5);

insert into Sighting (SuperHeroId, LocationId, DateSighted) values(1,1,"2017-10-01");
insert into Sighting (SuperHeroId, LocationId, DateSighted) values(2,1,"2017-10-01");
insert into Sighting (SuperHeroId, LocationId, DateSighted) values(3,1,"2017-09-01");
